// <auto-generated />
using System;
using Domain.DB;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Domain.Migrations
{
    [DbContext(typeof(DigitalSpaceDbContext))]
    [Migration("20220520025207_CrearBD")]
    partial class CrearBD
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.17")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Domain.Models.Person", b =>
                {
                    b.Property<int>("PersonID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("EmployeeID")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Document")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Telephone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("PersonID");

                    b.ToTable("Persons");

                    b.HasData(
                        new
                        {
                            PersonID = 1,
                            CreatedAt = new DateTime(2022, 5, 19, 21, 52, 7, 313, DateTimeKind.Local).AddTicks(921),
                            CreatedBy = "Juan Leon",
                            Document = "948426325",
                            Name = "Casey Heller",
                            Telephone = "(819) 961-9732"
                        },
                        new
                        {
                            PersonID = 2,
                            CreatedAt = new DateTime(2022, 5, 19, 21, 52, 7, 313, DateTimeKind.Local).AddTicks(921),
                            CreatedBy = "Juan Leon",
                            Document = "141139918",
                            Name = "Kristi Runte",
                            Telephone = "881-829-7031 x15056"
                        },
                        new
                        {
                            PersonID = 3,
                            CreatedAt = new DateTime(2022, 5, 19, 21, 52, 7, 313, DateTimeKind.Local).AddTicks(921),
                            CreatedBy = "Juan Leon",
                            Document = "152008784",
                            Name = "Angel Ondricka",
                            Telephone = "213-357-1280 x9524"
                        },
                        new
                        {
                            PersonID = 4,
                            CreatedAt = new DateTime(2022, 5, 19, 21, 52, 7, 313, DateTimeKind.Local).AddTicks(921),
                            CreatedBy = "Juan Leon",
                            Document = "599894278",
                            Name = "Tommie Rosenbaum",
                            Telephone = "650-412-7858"
                        },
                        new
                        {
                            PersonID = 5,
                            CreatedAt = new DateTime(2022, 5, 19, 21, 52, 7, 313, DateTimeKind.Local).AddTicks(921),
                            CreatedBy = "Juan Leon",
                            Document = "216959548",
                            Name = "Heather Bins",
                            Telephone = "1-297-426-5374"
                        },
                        new
                        {
                            PersonID = 6,
                            CreatedAt = new DateTime(2022, 5, 19, 21, 52, 7, 313, DateTimeKind.Local).AddTicks(921),
                            CreatedBy = "Juan Leon",
                            Document = "396820505",
                            Name = "Willis Thiel",
                            Telephone = "449-331-9036 x283"
                        },
                        new
                        {
                            PersonID = 7,
                            CreatedAt = new DateTime(2022, 5, 19, 21, 52, 7, 313, DateTimeKind.Local).AddTicks(921),
                            CreatedBy = "Juan Leon",
                            Document = "691765718",
                            Name = "Alma Lockman",
                            Telephone = "(750) 722-8709 x7380"
                        },
                        new
                        {
                            PersonID = 8,
                            CreatedAt = new DateTime(2022, 5, 19, 21, 52, 7, 313, DateTimeKind.Local).AddTicks(921),
                            CreatedBy = "Juan Leon",
                            Document = "548745407",
                            Name = "Ann Corwin",
                            Telephone = "(495) 835-5005"
                        },
                        new
                        {
                            PersonID = 9,
                            CreatedAt = new DateTime(2022, 5, 19, 21, 52, 7, 313, DateTimeKind.Local).AddTicks(921),
                            CreatedBy = "Juan Leon",
                            Document = "676104089",
                            Name = "Danny Balistreri",
                            Telephone = "890-452-1986"
                        },
                        new
                        {
                            PersonID = 10,
                            CreatedAt = new DateTime(2022, 5, 19, 21, 52, 7, 313, DateTimeKind.Local).AddTicks(921),
                            CreatedBy = "Juan Leon",
                            Document = "747362185",
                            Name = "Melanie Jaskolski",
                            Telephone = "(232) 927-1015"
                        },
                        new
                        {
                            PersonID = 11,
                            CreatedAt = new DateTime(2022, 5, 19, 21, 52, 7, 313, DateTimeKind.Local).AddTicks(921),
                            CreatedBy = "Juan Leon",
                            Document = "988460931",
                            Name = "Gwen Blick",
                            Telephone = "838-747-7842 x148"
                        },
                        new
                        {
                            PersonID = 12,
                            CreatedAt = new DateTime(2022, 5, 19, 21, 52, 7, 313, DateTimeKind.Local).AddTicks(921),
                            CreatedBy = "Juan Leon",
                            Document = "247969364",
                            Name = "Maria Fritsch",
                            Telephone = "1-397-602-0946"
                        },
                        new
                        {
                            PersonID = 13,
                            CreatedAt = new DateTime(2022, 5, 19, 21, 52, 7, 313, DateTimeKind.Local).AddTicks(921),
                            CreatedBy = "Juan Leon",
                            Document = "249755410",
                            Name = "Charlene King",
                            Telephone = "832-440-2751"
                        },
                        new
                        {
                            PersonID = 14,
                            CreatedAt = new DateTime(2022, 5, 19, 21, 52, 7, 313, DateTimeKind.Local).AddTicks(921),
                            CreatedBy = "Juan Leon",
                            Document = "471782504",
                            Name = "Grady Schmidt",
                            Telephone = "1-546-676-3045 x50103"
                        },
                        new
                        {
                            PersonID = 15,
                            CreatedAt = new DateTime(2022, 5, 19, 21, 52, 7, 313, DateTimeKind.Local).AddTicks(921),
                            CreatedBy = "Juan Leon",
                            Document = "207903521",
                            Name = "Allan Rowe",
                            Telephone = "(330) 744-8105 x170"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
