// <auto-generated />
using System;
using Domain.DB;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Domain.Migrations
{
    [DbContext(typeof(DigitalSpaceDbContext))]
    [Migration("20220520035321_CrearBD")]
    partial class CrearBD
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.17")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Domain.Models.Person", b =>
                {
                    b.Property<int>("PersonID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("PersonID")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Document")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RolID")
                        .HasColumnType("int");

                    b.Property<string>("Telephone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("PersonID");

                    b.HasIndex("RolID");

                    b.ToTable("Person");

                    b.HasData(
                        new
                        {
                            PersonID = 1,
                            CreatedAt = new DateTime(2022, 5, 19, 22, 53, 21, 480, DateTimeKind.Local).AddTicks(1779),
                            CreatedBy = "Juan Leon",
                            Document = "128013937",
                            Name = "Kay Zboncak",
                            RolID = 2,
                            Telephone = "1-872-308-0179 x87057"
                        },
                        new
                        {
                            PersonID = 2,
                            CreatedAt = new DateTime(2022, 5, 19, 22, 53, 21, 480, DateTimeKind.Local).AddTicks(1779),
                            CreatedBy = "Juan Leon",
                            Document = "970156869",
                            Name = "Tom Koepp",
                            RolID = 3,
                            Telephone = "241-828-9693"
                        },
                        new
                        {
                            PersonID = 3,
                            CreatedAt = new DateTime(2022, 5, 19, 22, 53, 21, 480, DateTimeKind.Local).AddTicks(1779),
                            CreatedBy = "Juan Leon",
                            Document = "911402224",
                            Name = "Edna Paucek",
                            RolID = 1,
                            Telephone = "1-695-876-4567 x08538"
                        },
                        new
                        {
                            PersonID = 4,
                            CreatedAt = new DateTime(2022, 5, 19, 22, 53, 21, 480, DateTimeKind.Local).AddTicks(1779),
                            CreatedBy = "Juan Leon",
                            Document = "458363221",
                            Name = "Samuel Schneider",
                            RolID = 1,
                            Telephone = "269.422.4476 x07987"
                        },
                        new
                        {
                            PersonID = 5,
                            CreatedAt = new DateTime(2022, 5, 19, 22, 53, 21, 480, DateTimeKind.Local).AddTicks(1779),
                            CreatedBy = "Juan Leon",
                            Document = "104135530",
                            Name = "Salvador Steuber",
                            RolID = 1,
                            Telephone = "1-811-332-4240"
                        },
                        new
                        {
                            PersonID = 6,
                            CreatedAt = new DateTime(2022, 5, 19, 22, 53, 21, 480, DateTimeKind.Local).AddTicks(1779),
                            CreatedBy = "Juan Leon",
                            Document = "856721513",
                            Name = "Elbert Macejkovic",
                            RolID = 3,
                            Telephone = "(804) 888-5992 x866"
                        },
                        new
                        {
                            PersonID = 7,
                            CreatedAt = new DateTime(2022, 5, 19, 22, 53, 21, 480, DateTimeKind.Local).AddTicks(1779),
                            CreatedBy = "Juan Leon",
                            Document = "443774834",
                            Name = "Clara Hudson",
                            RolID = 2,
                            Telephone = "(795) 801-1588"
                        },
                        new
                        {
                            PersonID = 8,
                            CreatedAt = new DateTime(2022, 5, 19, 22, 53, 21, 480, DateTimeKind.Local).AddTicks(1779),
                            CreatedBy = "Juan Leon",
                            Document = "993313376",
                            Name = "Candice Wintheiser",
                            RolID = 3,
                            Telephone = "854.889.3583 x34869"
                        },
                        new
                        {
                            PersonID = 9,
                            CreatedAt = new DateTime(2022, 5, 19, 22, 53, 21, 480, DateTimeKind.Local).AddTicks(1779),
                            CreatedBy = "Juan Leon",
                            Document = "988760798",
                            Name = "Larry Keebler",
                            RolID = 2,
                            Telephone = "(588) 914-7439 x63416"
                        },
                        new
                        {
                            PersonID = 10,
                            CreatedAt = new DateTime(2022, 5, 19, 22, 53, 21, 480, DateTimeKind.Local).AddTicks(1779),
                            CreatedBy = "Juan Leon",
                            Document = "876653512",
                            Name = "Ivan Smith",
                            RolID = 2,
                            Telephone = "1-828-583-5344"
                        },
                        new
                        {
                            PersonID = 11,
                            CreatedAt = new DateTime(2022, 5, 19, 22, 53, 21, 480, DateTimeKind.Local).AddTicks(1779),
                            CreatedBy = "Juan Leon",
                            Document = "245124844",
                            Name = "Alicia Windler",
                            RolID = 1,
                            Telephone = "(609) 465-2129 x9827"
                        },
                        new
                        {
                            PersonID = 12,
                            CreatedAt = new DateTime(2022, 5, 19, 22, 53, 21, 480, DateTimeKind.Local).AddTicks(1779),
                            CreatedBy = "Juan Leon",
                            Document = "879848412",
                            Name = "Jackie Kozey",
                            RolID = 1,
                            Telephone = "546-518-3136 x74628"
                        },
                        new
                        {
                            PersonID = 13,
                            CreatedAt = new DateTime(2022, 5, 19, 22, 53, 21, 480, DateTimeKind.Local).AddTicks(1779),
                            CreatedBy = "Juan Leon",
                            Document = "813150247",
                            Name = "Kristi Legros",
                            RolID = 1,
                            Telephone = "715.445.0688"
                        },
                        new
                        {
                            PersonID = 14,
                            CreatedAt = new DateTime(2022, 5, 19, 22, 53, 21, 480, DateTimeKind.Local).AddTicks(1779),
                            CreatedBy = "Juan Leon",
                            Document = "381689866",
                            Name = "Sidney Klocko",
                            RolID = 1,
                            Telephone = "(880) 734-2588"
                        },
                        new
                        {
                            PersonID = 15,
                            CreatedAt = new DateTime(2022, 5, 19, 22, 53, 21, 480, DateTimeKind.Local).AddTicks(1779),
                            CreatedBy = "Juan Leon",
                            Document = "752046397",
                            Name = "Glen Wintheiser",
                            RolID = 3,
                            Telephone = "1-616-589-3351"
                        });
                });

            modelBuilder.Entity("Domain.Models.Rol", b =>
                {
                    b.Property<int>("RolID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("RolID")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("RolID");

                    b.ToTable("Rol");

                    b.HasData(
                        new
                        {
                            RolID = 1,
                            CreatedAt = new DateTime(2022, 5, 19, 22, 53, 21, 445, DateTimeKind.Local).AddTicks(3949),
                            CreatedBy = "Juan Leon",
                            Name = "Administrador"
                        },
                        new
                        {
                            RolID = 2,
                            CreatedAt = new DateTime(2022, 5, 19, 22, 53, 21, 446, DateTimeKind.Local).AddTicks(1109),
                            CreatedBy = "Juan Leon",
                            Name = "Cliente"
                        },
                        new
                        {
                            RolID = 3,
                            CreatedAt = new DateTime(2022, 5, 19, 22, 53, 21, 446, DateTimeKind.Local).AddTicks(1121),
                            CreatedBy = "Juan Leon",
                            Name = "Vendedor"
                        });
                });

            modelBuilder.Entity("Domain.Models.Person", b =>
                {
                    b.HasOne("Domain.Models.Rol", "Rol")
                        .WithMany()
                        .HasForeignKey("RolID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Rol");
                });
#pragma warning restore 612, 618
        }
    }
}
